infer_cfgs:
  # The deepspeed configuration
  ds_cfgs: ds_z3_config.json
  vllm_cfgs: vllm_basic.json
  
default:
  # Evaluation configurations
  eval_cfgs:
    # Output directory name
    output_dir: null
    # Num shot
    n_shot: 8
    # Use Chain of Thought
    cot: false
  # Configuration for data
  data_cfgs:
    # Task name
    task: ''
    # Task directory
    task_dir: openai/openai_humaneval
    # Evaluation split
    split: 'test'

  # Model configurations
  model_cfgs:
    model_id: Qwen2-7B
    # Pretrained model name or path
    model_name_or_path: /aifs4su/yaodong/models/qwen/Qwen2-7B
    # Chat template
    chat_template: Qwen
    # The max token length
    model_max_length: 2048