infer_cfgs:
  # The deepspeed configuration
  ds_cfgs: ds_z3_config.json
  # vllm_cfgs: vllm_basic.json

default:
  # Evaluation configurations
  eval_cfgs:
    # batch_size: 1
    # Seed for random number generator
    seed: 0
    # Output directory name
    output_dir: null
    # Num shot
    n_shot: 5
    # Evaluation method
    action: generation
  # Configuration for data
  data_cfgs:
    # Task name
    task: [ARC-Challenge, ARC-Easy]
    # Task directory
    task_dir: allenai/ai2_arc
    # Evaluation split
    split: test

  # Model configurations
  model_cfgs:
    model_id: alpaca-7b-reproduced
    # Pretrained model name or path
    model_name_or_path: /aifs4su/yaodong/models/alpaca-7b-reproduced
    # Chat template
    chat_template: PKUSafeRLHF
    # Whether to trust remote code
    trust_remote_code: True
    # The max token length
    model_max_length: 2048
